apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  selector:
    matchLabels:
      app: kubernetes
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: kubernetes
          image: che444/kubernetes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
